from rdflib import Graph, Namespace, URIRef, Literal,BNode

rdf = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
rdfs = Namespace("http://www.w3.org/2000/01/rdf-schema#")
schema = Namespace("http://schema.org/")
pto = Namespace("http://www.productontology.org/id/")
dct = Namespace("http://purl.org/dc/terms/")
skos = Namespace("http://www.w3.org/2004/02/skos/core#")
eco = Namespace("http://www.ebusiness-unibw.org/ontologies/eclass/5.1.4#")
sosa = Namespace("http://www.w3.org/ns/sosa/")
td = Namespace("https://www.w3.org/2019/wot/td#")
onto = Namespace("https://ci.mines-stetienne.fr/kg/ontology#")
hctl = Namespace("https://www.w3.org/2019/wot/hypermedia#")
htv = Namespace("http://www.w3.org/2011/http#")                 
js = Namespace("https://www.w3.org/2019/wot/json-schema#")            
                 
g = Graph()
machine = BNode()
Operation = BNode()

g.bind("rdf", rdf)
g.bind("rdfs", rdfs)
g.bind("schema", schema)
g.bind("pto", pto)
g.bind("dct", dct)
g.bind("skos", skos)
g.bind("eco", eco)
g.bind("sosa", sosa)
g.bind("td", td)
g.bind("onto", onto)
g.bind("hctl", hctl)
g.bind("htv", htv)
g.bind("js", js)

Motor = URIRef("https://ci.mines-stetienne.fr/kg/itmfactory/dx10/M2")
g.add((Motor, rdf.type, pto.Brushless_DC_electric_motor))
g.add((Motor, rdf.type, eco.C_AJZ041005))
g.add((Motor, rdfs.label, Literal("Brushless Motor", lang=("en"))))
g.add((Motor,  skos.prefLabel, Literal("M2")))
g.add((Motor, rdfs.comment, Literal("Brushless motor for movable part (hopper) on the DX10 of the IT'm factory", lang=("en"))))
g.add((Motor, schema.manufacture, Literal("SIEMENS")))
g.add((Motor, dct.identifier, Literal("https://mall.industry.siemens.com/mall/en/kr/Catalog/Product/1FL6024-2AF21-1AA1")))
g.add((Motor, td.hasPropertyAffordance, machine))
g.add((machine, rdf.type, td.PropertyAffordance))
g.add((machine, rdf.type, js.IntegerSchema))
g.add((machine, dct.title, Literal("Axe_Remplissage_Position_int")))
g.add((machine, dct.description, Literal("It is used to read and write the speed of the movable part (hopper) on the DX10 Machine of the IT'm factory.", lang=("en"))))
g.add((machine, js.readOnly, Literal("False")))
g.add((machine, js.writeOnly, Literal("False")))
g.add((machine, td.hasForm, Operation))             
g.add((Operation, rdf.type, hctl.Form))
g.add((Operation, htv.methodName, Literal("GET")))
g.add((Operation, hctl.forContentType, Literal("application/json")))
g.add((Operation, hctl.hasOperationType, td.readProperty))
g.add((Operation, hctl.hasOperationType, td.writeProperty))
g.add((Operation, hctl.hasTarget, Literal("https://ci.mines-stetienne.fr/simu/fillingWorkshop/properties/Axe_Remplissage_Position_int")))
g.add((machine, td.isObservable, Literal("False")))
g.add((machine, td.name, Literal("Axe_Remplissage_Position_int")))

print(g.serialize(r"C:\Users\Siva Ratnam Pachava\OneDrive\Desktop\InternshipM1\DX10\M2.ttl" , format='turtle'))