from rdflib import Graph, Namespace, URIRef, Literal,BNode

rdf = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
rdfs = Namespace("http://www.w3.org/2000/01/rdf-schema#")
schema = Namespace("http://schema.org/")
pto = Namespace("http://www.productontology.org/id/")
dct = Namespace("http://purl.org/dc/terms/")
skos = Namespace("http://www.w3.org/2004/02/skos/core#")
eco = Namespace("http://www.ebusiness-unibw.org/ontologies/eclass/5.1.4#")
sosa = Namespace("http://www.w3.org/ns/sosa/")
td = Namespace("https://www.w3.org/2019/wot/td#")
onto = Namespace("https://ci.mines-stetienne.fr/kg/ontology#")
hctl = Namespace("https://www.w3.org/2019/wot/hypermedia#")
htv = Namespace("http://www.w3.org/2011/http#")                 
js = Namespace("https://www.w3.org/2019/wot/json-schema#")            
                 
g = Graph()
machine = BNode()
Operation = BNode()

g.bind("rdf", rdf)
g.bind("rdfs", rdfs)
g.bind("schema", schema)
g.bind("pto", pto)
g.bind("dct", dct)
g.bind("skos", skos)
g.bind("eco", eco)
g.bind("sosa", sosa)
g.bind("td", td)
g.bind("onto", onto)
g.bind("hctl", hctl)
g.bind("htv", htv)
g.bind("js", js)

Cylinder = URIRef("https://ci.mines-stetienne.fr/kg/itmfactory/dx10/B4")
g.add((Cylinder, rdf.type, pto.Level_Sensor))
g.add((Cylinder, rdf.type, pto.Sensor))
g.add((Cylinder, rdf.type, eco.C_AGZ376003))
g.add((Cylinder, rdfs.Label, Literal("Diffuse sensor with background suppression")))
g.add((Cylinder, skos.prefLabel, Literal("B4")))
g.add((Cylinder, rdfs.comment, Literal("It is used to indicate the level of the product in the container.", lang=("en"))))
g.add((Cylinder, schema.manufacture, Literal("Leuze")))
g.add((Cylinder, sosa.observes,  Literal("Indicates the amount of product in the hopper on DX10 machine of the IT'm factory.", lang=("en"))))
g.add((Cylinder, dct.identifier, Literal("https://www.leuze.com/en/usa/products_us/switching_sensors_us/optical_sensors_us/photoelectric_sensors_light_scanners_cubic_us/5_series_us/lichttaster_mit_hintergrundausblendung_us_5/ht_5_us/selector.php?supplier_aid=50135262&grp_id=1467795393506&lang=eng")))
g.add((Cylinder, td.hasPropertyAffordance, machine))
g.add((machine, rdf.type, td.PropertyAffordance))
g.add((machine, rdf.type, js.NumberSchema))
g.add((machine, rdf.type, onto.LiquidVolume))
g.add((machine, dct.title, Literal("Presence Produit")))
g.add((machine, dct.description, Literal("Indicates tank reaches to ideal/intial position on DX10 machine of the IT'm factory.", lang=("en"))))
g.add((machine, js.readOnly, Literal("True")))
g.add((machine, js.writeOnly, Literal("False")))
g.add((machine, td.hasForm, Operation))             
g.add((Operation, rdf.type, hctl.Form))
g.add((Operation, htv.methodName, Literal("GET")))
g.add((Operation, hctl.forContentType, Literal("application/json")))
g.add((Operation, hctl.hasOperationType, td.readProperty))
g.add((Operation, hctl.hasTarget, Literal("https://ci.mines-stetienne.fr/simu/fillingWorkshop/properties/PresenceProduit")))
g.add((machine, td.isObservable, Literal("False")))
g.add((machine, td.name, Literal("PresenceProduit")))

print(g.serialize(r"C:\Users\Siva Ratnam Pachava\OneDrive\Desktop\InternshipM1\DX10\B4.ttl", format='turtle'))