from rdflib import Graph, Namespace, URIRef, Literal,BNode

rdf = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
rdfs = Namespace("http://www.w3.org/2000/01/rdf-schema#")
schema = Namespace("http://schema.org/")
pto = Namespace("http://www.productontology.org/id/")
dct = Namespace("http://purl.org/dc/terms/")
skos = Namespace("http://www.w3.org/2004/02/skos/core#")
eco = Namespace("http://www.ebusiness-unibw.org/ontologies/eclass/5.1.4#")
sosa = Namespace("http://www.w3.org/ns/sosa/")
td = Namespace("https://www.w3.org/2019/wot/td#")
onto = Namespace("https://ci.mines-stetienne.fr/kg/ontology#")
hctl = Namespace("https://www.w3.org/2019/wot/hypermedia#")
htv = Namespace("http://www.w3.org/2011/http#")                 
js = Namespace("https://www.w3.org/2019/wot/json-schema#")            
                 
g = Graph()
machine = BNode()
Operation = BNode()

g.bind("rdf", rdf)
g.bind("rdfs", rdfs)
g.bind("schema", schema)
g.bind("pto", pto)
g.bind("dct", dct)
g.bind("skos", skos)
g.bind("eco", eco)
g.bind("sosa", sosa)
g.bind("td", td)
g.bind("onto", onto)
g.bind("hctl", hctl)
g.bind("htv", htv)
g.bind("js", js)

Sensor = URIRef("https://ci.mines-stetienne.fr/kg/itmfactory/vl10/B13")
g.add((Sensor, rdf.type, pto.Light_curtain))
g.add((Sensor, rdf.type, eco.C_AKE650002))
g.add((Sensor, rdfs.label, Literal("Safety light curtains miniTwin", lang=("en"))))
g.add((Sensor,  skos.prefLabel, Literal("B13")))
g.add((Sensor, rdfs.comment, Literal("Mini-Twin safety light curtains are used to perform real-time optimization of products and production processes", lang=("en"))))
g.add((Sensor, schema.manufacture, Literal("SICK Sensor Intelligence")))
g.add((Sensor, sosa.observes, Literal("By using miniTwin work can be performed unhindered at machines, accelerating production processes.", lang=("en"))))
g.add((Sensor, schema.url, Literal("https://www.sick.com/fr/fr/barrages-immateriels-de-securite/barrages-immateriels-de-securite/minitwin/c4mt-01214abb03bb0/p/p123668")))
g.add((Sensor, td.hasPropertyAffordance, machine))
g.add((machine, rdf.type, td.PropertyAffordance))
g.add((machine, rdf.type, js.BooleanSchema))
g.add((machine, dct.title, Literal("Conveyor drive status")))
g.add((machine, dct.description, Literal("Indicates the status/condiation/position of the conveyor belt drive on the VL10 Machine of the IT'm factory.", lang=("en"))))
g.add((machine, js.readOnly, Literal("True")))
g.add((machine, js.writeOnly, Literal("False")))
g.add((machine, td.hasForm, Operation))             
g.add((Operation, rdf.type, hctl.Form))
g.add((Operation, htv.methodName, Literal("GET")))
g.add((Operation, hctl.forContentType, Literal("application/json")))
g.add((Operation, hctl.hasOperationType, td.readProperty))
g.add((Operation, hctl.hasTarget, Literal("https://ci.mines-stetienne.fr/simu/storageRack/properties/Défaut_var_convoyeur")))
g.add((machine, td.isObservable, Literal("False")))
g.add((machine, td.name, Literal("Défaut_var_convoyeur")))

print(g.serialize(r"C:\Users\Siva Ratnam Pachava\OneDrive\Desktop\InternshipM1\VL10\B13.ttl", format='turtle'))