from rdflib import Graph, Namespace, URIRef, Literal,BNode

rdf = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
rdfs = Namespace("http://www.w3.org/2000/01/rdf-schema#")
schema = Namespace("http://schema.org/")
pto = Namespace("http://www.productontology.org/id/")
dct = Namespace("http://purl.org/dc/terms/")
skos = Namespace("http://www.w3.org/2004/02/skos/core#")
eco = Namespace("http://www.ebusiness-unibw.org/ontologies/eclass/5.1.4#")
sosa = Namespace("http://www.w3.org/ns/sosa/")
td = Namespace("https://www.w3.org/2019/wot/td#")
onto = Namespace("https://ci.mines-stetienne.fr/kg/ontology#")
hctl = Namespace("https://www.w3.org/2019/wot/hypermedia#")
htv = Namespace("http://www.w3.org/2011/http#")                 
js = Namespace("https://www.w3.org/2019/wot/json-schema#")            
                 
g = Graph()
machine = BNode()
Operation = BNode()

g.bind("rdf", rdf)
g.bind("rdfs", rdfs)
g.bind("schema", schema)
g.bind("pto", pto)
g.bind("dct", dct)
g.bind("skos", skos)
g.bind("eco", eco)
g.bind("sosa", sosa)
g.bind("td", td)
g.bind("onto", onto)
g.bind("hctl", hctl)
g.bind("htv", htv)
g.bind("js", js)

Sensor = URIRef("https://ci.mines-stetienne.fr/kg/itmfactory/vl10/B14")
g.add((Sensor, rdf.type, pto.Position_sensor))
g.add((Sensor, rdf.type, eco.C_AGZ258004))
g.add((Sensor, rdfs.label, Literal("Position_sensor")))
g.add((Sensor,  skos.prefLabel, Literal("B14")))
g.add((Sensor, rdfs.comment, Literal("Position Sensors are used to measure linear motion, In vl10 it has venturi with vacuum switch and 2 detection thresholds", lang=("en"))))
g.add((Sensor, sosa.observes, Literal("It detects linear motion of the cartecian robot in Y-Axis direction on the VL10 Machine of the IT'm factory.", lang=("en"))))
g.add((Sensor, schema.manufacture, Literal("SICK Sensor Intelligence")))
g.add((Sensor, dct.identifier, Literal("https://www.sick.com/fr/en/magnetic-cylinder-sensors/position-sensors/mps-t/mps-224tltq0/p/p318150?ff_data=JmZmX2lkPXAzMTgxNTAmZmZfbWFzdGVySWQ9cDMxODE1MCZmZl90aXRsZT1NUFMtMjI0VExUUTAmZmZfcXVlcnk9SU8tTElOSyZmZl9wb3M9MjAmZmZfb3JpZ1Bvcz0yMCZmZl9wYWdlPTEmZmZfcGFnZVNpemU9MjQmZmZfb3JpZ1BhZ2VTaXplPTI0JmZmX3NpbWk9OTQuMA==")))
g.add((Sensor, td.hasPropertyAffordance, machine))
g.add((machine, rdf.type, td.PropertyAffordance))
g.add((machine, rdf.type, js.BooleanSchema))
g.add((machine, dct.title, Literal("Y Axis airlock cylinder status")))
g.add((machine, dct.description, Literal("Indicates the status/condiation/position of the Y Axis airlock cylinder on the VL10 Machine of the IT'm factory.", lang=("en"))))
g.add((machine, js.readOnly, Literal("True")))
g.add((machine, js.writeOnly, Literal("False")))
g.add((machine, td.hasForm, Operation))             
g.add((Operation, rdf.type, hctl.Form))
g.add((Operation, htv.methodName, Literal("GET")))
g.add((Operation, hctl.forContentType, Literal("application/json")))
g.add((Operation, hctl.hasOperationType, td.readProperty))
g.add((Operation, hctl.hasTarget, Literal("http://localhost:3001/ns=2;s=Channel_test2.Magasin%20vertical.Ouverture_Pinces")))
g.add((machine, td.isObservable, Literal("False")))
g.add((machine, td.name, Literal("Ouverture_Pinces")))

print(g.serialize(r"C:\Users\Siva Ratnam Pachava\OneDrive\Desktop\InternshipM1\VL10\B14.ttl", format='turtle'))