from rdflib import Graph, Namespace, URIRef, Literal,BNode

rdf = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
rdfs = Namespace("http://www.w3.org/2000/01/rdf-schema#")
schema = Namespace("http://schema.org/")
pto = Namespace("http://www.productontology.org/id/")
dct = Namespace("http://purl.org/dc/terms/")
skos = Namespace("http://www.w3.org/2004/02/skos/core#")
eco = Namespace("http://www.ebusiness-unibw.org/ontologies/eclass/5.1.4#")
sosa = Namespace("http://www.w3.org/ns/sosa/")
td = Namespace("https://www.w3.org/2019/wot/td#")
onto = Namespace("https://ci.mines-stetienne.fr/kg/ontology#")
hctl = Namespace("https://www.w3.org/2019/wot/hypermedia#")
htv = Namespace("http://www.w3.org/2011/http#")                 
js = Namespace("https://www.w3.org/2019/wot/json-schema#")            
                 
g = Graph()
machine = BNode()
Operation = BNode()

g.bind("rdf", rdf)
g.bind("rdfs", rdfs)
g.bind("schema", schema)
g.bind("pto", pto)
g.bind("dct", dct)
g.bind("skos", skos)
g.bind("eco", eco)
g.bind("sosa", sosa)
g.bind("td", td)
g.bind("onto", onto)
g.bind("hctl", hctl)
g.bind("htv", htv)
g.bind("js", js)

Motor = URIRef("https://ci.mines-stetienne.fr/kg/itmfactory/vl10/M1")
g.add((Motor, rdf.type, pto.wormgear))
g.add((Motor, rdf.type, pto.motor))
g.add((Motor, rdf.type, eco.C_AKH3960022))
g.add((Motor, rdfs.label, Literal("WORM GEAR REDUCER Motor", lang=("en"))))
g.add((Motor,  skos.prefLabel, Literal("M1")))
g.add((Motor, rdfs.comment, Literal("Motor for conveyor belt on the VL10 of the IT'm factory", lang=("en"))))
g.add((Motor, schema.manufacture, Literal("Motovario")))
g.add((Motor, dct.identifier, Literal("https://www.motovario.com/eng/products/worm-gear-reducers--vsf-series/worm-gear-reducers-combined-and-with-pre-stage-reduction-unit")))
g.add((Motor, td.hasPropertyAffordance, machine))
g.add((machine, rdf.type, td.PropertyAffordance))
g.add((machine, rdf.type, js.NumberSchema))
g.add((machine, rdf.type, onto.ConveyorSpeed))
g.add((machine, dct.title, Literal("Conveyor Speed")))
g.add((machine, dct.description, Literal("It is used to read and write the speed of the conveyor belt on the VL10 Machine of the IT'm factory.", lang=("en"))))
g.add((machine, js.readOnly, Literal("False")))
g.add((machine, js.writeOnly, Literal("False")))
g.add((machine, td.hasForm, Operation))             
g.add((Operation, rdf.type, hctl.Form))
g.add((Operation, htv.methodName, Literal("GET")))
g.add((Operation, hctl.forContentType, Literal("application/json")))
g.add((Operation, hctl.hasOperationType, td.readProperty))
g.add((Operation, hctl.hasOperationType, td.writeProperty))
g.add((Operation, hctl.hasTarget, Literal("http://localhost:3001/ns=2;s=Channel_test2.Magasin%20vertical.Consigne%20vitesse%20convoyeur")))
g.add((machine, td.isObservable, Literal("False")))
g.add((machine, td.name, Literal("Consigne vitesse convoyeur")))

print(g.serialize(r"C:\Users\Siva Ratnam Pachava\OneDrive\Desktop\InternshipM1\VL10\M1.ttl" , format='turtle'))