from rdflib import Graph, Namespace, URIRef, Literal, BNode

rdf = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
rdfs = Namespace("http://www.w3.org/2000/01/rdf-schema#")
schema = Namespace("http://schema.org/")
pto = Namespace("http://www.productontology.org/id/")
dct = Namespace("http://purl.org/dc/terms/")
skos = Namespace("http://www.w3.org/2004/02/skos/core#")
eco = Namespace("http://www.ebusiness-unibw.org/ontologies/eclass/5.1.4#")
sosa = Namespace("http://www.w3.org/ns/sosa/")
td = Namespace("https://www.w3.org/2019/wot/td#")
onto = Namespace("https://ci.mines-stetienne.fr/kg/ontology#")
hctl = Namespace("https://www.w3.org/2019/wot/hypermedia#")
htv = Namespace("http://www.w3.org/2011/http#")                 
js = Namespace("https://www.w3.org/2019/wot/json-schema#")            
                 
g = Graph()
machine = BNode()
Operation = BNode()

g.bind("rdf", rdf)
g.bind("rdfs", rdfs)
g.bind("schema", schema)
g.bind("pto", pto)
g.bind("dct", dct)
g.bind("skos", skos)
g.bind("eco", eco)
g.bind("sosa", sosa)
g.bind("td", td)
g.bind("onto", onto)
g.bind("hctl", hctl)
g.bind("htv", htv)
g.bind("js", js)

Switch = URIRef("https://ci.mines-stetienne.fr/kg/itmfactory/xy10/B2")
g.add((Switch, rdf.type, pto.Reed_switch))
g.add((Switch, rdf.type, eco.C_AAX025004))
g.add((Switch, skos.prefLabel, Literal("B2")))
g.add((Switch, rdfs.Label, Literal("Reed Switch, Direct Mounting, Grommet, In-line")))
g.add((Switch, rdfs.comment, Literal("It consists of a pair of ferromagnetic flexible metal contacts and these contacts are normally closed and open when a magnetic field is applied.", lang=("en"))))
g.add((Switch, sosa.observes, Literal("It indicates the contact(Bar) is closed and it is not picking the tray from tray gravity on xy10 machine.", lang=("en"))))
g.add((Switch, schema.manufacturer, Literal("SMC")))
g.add((Switch, dct.identifier, Literal("https://www.smc.eu/en-eu/products/d-a90-a93-a96-reed-switch-direct-mounting-grommet-in-line~75484~cfg?partNumber=D-A93")))
g.add((Switch, td.hasPropertyAffordance, machine))
g.add((machine, rdf.type, td.PropertyAffordance))
g.add((machine, rdf.type, js.BooleanSchema))
g.add((machine, dct.title, Literal("Cylinder Bar Returns")))
g.add((machine, dct.description, Literal("Indicates the contact is closed and it is not picking the tray from tray gravity on xy10 machine.", lang=("en"))))
g.add((machine, js.readOnly, Literal("True")))
g.add((machine, js.writeOnly, Literal("False")))
g.add((machine, td.hasForm, Operation))             
g.add((Operation, rdf.type, hctl.Form))
g.add((Operation, htv.methodName, Literal("GET")))
g.add((Operation, hctl.forContentType, Literal("application/json")))
g.add((Operation, hctl.hasOperationType, td.readProperty))
g.add((Operation, hctl.hasTarget, Literal("https://ci.mines-stetienne.fr/simu/storageRack/properties/Depil_Barq_Rentre_B2")))
g.add((machine, td.isObservable, Literal("False")))
g.add((machine, td.name, Literal("Depil_Barq_Rentre_B2")))

print(g.serialize(r"C:\Users\Siva Ratnam Pachava\OneDrive\Desktop\InternshipM1\XY10\B2.ttl" , format='ttl'))