from rdflib import Graph, Namespace, URIRef, Literal,BNode

rdf = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
rdfs = Namespace("http://www.w3.org/2000/01/rdf-schema#")
schema = Namespace("http://schema.org/")
pto = Namespace("http://www.productontology.org/id/")
dct = Namespace("http://purl.org/dc/terms/")
skos = Namespace("http://www.w3.org/2004/02/skos/core#")
eco = Namespace("http://www.ebusiness-unibw.org/ontologies/eclass/5.1.4#")
sosa = Namespace("http://www.w3.org/ns/sosa/")
td = Namespace("https://www.w3.org/2019/wot/td#")
onto = Namespace("https://ci.mines-stetienne.fr/kg/ontology#")
hctl = Namespace("https://www.w3.org/2019/wot/hypermedia#")
htv = Namespace("http://www.w3.org/2011/http#")                 
js = Namespace("https://www.w3.org/2019/wot/json-schema#")            
                 
g = Graph()
machine = BNode()
Operation = BNode()

g.bind("rdf", rdf)
g.bind("rdfs", rdfs)
g.bind("schema", schema)
g.bind("pto", pto)
g.bind("dct", dct)
g.bind("skos", skos)
g.bind("eco", eco)
g.bind("sosa", sosa)
g.bind("td", td)
g.bind("onto", onto)
g.bind("hctl", hctl)
g.bind("htv", htv)
g.bind("js", js)

Sensor = URIRef("https://ci.mines-stetienne.fr/kg/itmfactory/xy10/B4")
g.add((Sensor, rdf.type, pto.Photoelectric_sensor))
g.add((Sensor, rdf.type,  sosa.Sensor))
g.add((Sensor, rdf.type, eco.C_AKP251002))
g.add((Sensor, rdfs.label, Literal("Polarized retro-reflective photoelectric sensor")))
g.add((Sensor, skos.prefLabel, Literal("B4")))
g.add((Sensor, rdfs.comment, Literal("photoelectric sensor sensed presence of an object by using a light transmitter", lang=("en"))))
g.add((Sensor, sosa.observes, Literal("It indicates tray is present at picking position on xy10 machine", lang=("en"))))
g.add((Sensor, schema.manufacture, Literal("Leuze")))
g.add((Sensor, dct.identifier, Literal("https://www.leuze.com/en/usa/products_us/switching_sensors_us/optical_sensors_us/photoelectric_sensors_light_scanners_cubic_us/5_series_us/retro_reflective_photoelectric_sensors_us_2/prk5_us/selector.php?supplier_aid=50128200&grp_id=A1-1-1-1-3-2-1&lang=eng")))
g.add((Sensor, td.hasPropertyAffordance, machine))
g.add((machine, rdf.type, td.PropertyAffordance))
g.add((machine, rdf.type, js.BooleanSchema))
g.add((machine, rdf.type, onto.OpticalSensorStatus))
g.add((machine, dct.title, Literal("Tray Presence at Pickup Position")))
g.add((machine, dct.description, Literal("Indicates tray is present at picking position on xy10 machine of the IT'm factory.", lang=("en"))))
g.add((machine, js.readOnly, Literal("True")))
g.add((machine, js.writeOnly, Literal("False")))
g.add((machine, td.hasForm, Operation))             
g.add((Operation, rdf.type, hctl.Form))
g.add((Operation, htv.methodName, Literal("GET")))
g.add((Operation, hctl.forContentType, Literal("application/json")))
g.add((Operation, hctl.hasOperationType, td.readProperty))
g.add((Operation, hctl.hasTarget, Literal("https://ci.mines-stetienne.fr/simu/packagingWorkshop/properties/Presence_Barq_B4")))
g.add((machine, td.isObservable, Literal("False")))
g.add((machine, td.name, Literal("Presence_Barq_B4")))

print(g.serialize(r"C:\Users\Siva Ratnam Pachava\OneDrive\Desktop\InternshipM1\XY10\B4.ttl", format='turtle'))
